/**
 * Docker Compose file generation
 */

import { dirname, join } from "node:path";
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import chalk from "chalk";
import type { ConfigPaths, InfraConfig } from "./config.js";
import { DEFAULTS } from "./config.js";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ENTRYPOINT_PATH = join(__dirname, "..", "..", "templates", "entrypoint.ts");

/**
 * Read .env file and extract variable names
 */
function getEnvVarNames(baseDir: string): string[] {
  const envPath = join(baseDir, ".env");
  if (!existsSync(envPath)) {
    return [];
  }

  const content = readFileSync(envPath, "utf-8");
  const varNames: string[] = [];

  for (const line of content.split("\n")) {
    const trimmed = line.trim();
    // Skip comments and empty lines
    if (!trimmed || trimmed.startsWith("#")) continue;

    // Extract variable name (before the =)
    const match = trimmed.match(/^([A-Z_][A-Z0-9_]*)=/);
    if (match) {
      varNames.push(match[1]);
    }
  }

  return varNames;
}

/**
 * Generate docker-compose.yml content from configuration
 */
export function generateComposeContent(
  config: InfraConfig,
  baseDir: string
): string {
  const project = config.project;
  const image = config.docker?.image || DEFAULTS.image;
  const skillsPath = config.docker?.skills_path
    ? config.docker.skills_path.startsWith("/")
      ? config.docker.skills_path
      : join(baseDir, config.docker.skills_path)
    : null;

  let compose = `# Generated by polyclaw
# Do not edit manually - edit polyclaw.json5 and regenerate

name: ${project}

services:
`;

  // Get env vars from .env file
  const envVars = getEnvVarNames(baseDir);
  const envLines = envVars.map((v) => `      ${v}: \${${v}}`).join("\n");

  for (const [name, inst] of Object.entries(config.instances)) {
    const skillsVolume = skillsPath
      ? `\n      - ${skillsPath}:/skills-custom:ro`
      : "";

    // Combine global volumes + instance-specific volumes
    const globalVolumes = config.docker?.volumes || [];
    const instanceVolumes = inst.volumes || [];
    const allVolumes = [...globalVolumes, ...instanceVolumes];

    const extraVolumes = allVolumes
      .map((v) => {
        const mode = v.mode || "rw";
        return `\n      - "${v.host}:${v.container}:${mode}"`;
      })
      .join("");

    compose += `  ${name}:
    image: ${image}
    container_name: ${project}-${name}
    environment:
      HOME: /home/node
${envLines}
    volumes:
      - ./instances/${name}/config:/home/node/.openclaw
      - ./instances/${name}/workspace:/home/node/.openclaw/workspace${skillsVolume}${extraVolumes}
      - ${ENTRYPOINT_PATH}:/app/entrypoint.ts:ro
    ports:
      - "${inst.port}:18789"
    entrypoint: ["node", "--experimental-strip-types", "/app/entrypoint.ts"]
    command: ["--bind", "lan"]
    restart: unless-stopped

`;
  }

  return compose;
}

/**
 * Generate and write docker-compose.yml file
 */
export function generateComposeFile(
  config: InfraConfig,
  paths: ConfigPaths
): void {
  console.log(chalk.green("=== Generating docker-compose.yml ==="));

  const content = generateComposeContent(config, paths.baseDir);
  writeFileSync(paths.composeFile, content);

  const count = Object.keys(config.instances).length;
  console.log(
    `  ${chalk.green("OK")} docker-compose.yml generated with ${count} service(s)`
  );
}
